export const url_github = "https://github.com/charles-thuntn";
export const url_linkedIn = "https://www.linkedin.com/in/thu-nguyen-a8954129a/";
export const url_portfolio = "https://charlesnguyen.vercel.app";
export const numberphone = "0326217691";
export const email = "nthu240@gmail.com";
export const name_resume = "Resume-Thu-Nguyen";
export const design_by_footer = "Thu Nguyen";
export const number_project = 10
export const years_experience = 3